version: "3.7"

services:
  nginx-pm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    env_file: .env
    environment:
      DB_MYSQL_HOST: nginx-pm-db
      DB_MYSQL_PORT: '${DB_MYSQL_PORT}'
      DB_MYSQL_USER: '${DB_MYSQL_USER}'
      DB_MYSQL_PASSWORD: '${DB_MYSQL_PASSWORD}'
      DB_MYSQL_NAME: '${DB_MYSQL_NAME}'
      DISABLE_IPV6: 'true'
    volumes:
      - nginxpm-data:/data
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - nginx-pm-db
    networks:
      - net
      - nginx-pm-network

  nginx-pm-db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nginx-pm-network

volumes:
  nginxpm-data:
  mysql-data:
  letsencrypt:

networks:
  nginx-pm-network:
    external: true
  net:
    external: true
