version: '3.1'

services:

  wp-db1:
    image: mariadb:10.6.5-focal
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - nginx-pm-network

  wordpress1:
    depends_on:
      - wp-db1
    image: wordpress:5.9-php8.1-fpm-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: wp-db1
      WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'
    volumes:
      - wordpress:/var/www/html
    networks:
      - nginx-pm-network

  nginx-wp1:
    depends_on:
      - wordpress1
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - wordpress/:/var/www/html
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - nginx-pm-network

volumes:
  db-data:
  wordpress:

networks:
  nginx-pm-network:
    external: true
