version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
      - .env
    environment:
      # id {username}  - command to see PUID & PGID
      PUID: '${PUID}'
      PGID: '${PGID}'
      TZ: '${TZ}'
      SERVERURL: '${SERVERURL}' # auto - for automatic Public IP detect
      SERVERPORT: '${SERVER_PORT}' #for config file
      PEERS: '${PEERS}' #clients count
      PEERDNS: '${PEERDNS}' #optional
      INTERNAL_SUBNET: '${INTERNAL_SUBNET}' #optional
      ALLOWEDIPS: '${ALLOWEDIPS}' #optional
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - nginx-pm-network

networks:
  nginx-pm-network:
    external: true
